#!/bin/sh

# TODO don't run if .guard-jruby-rspec doesn't exist
# instead, warn that guard must be (re)started

touch .guard-jruby-rspec-pipe
rm .guard-jruby-rspec

# todo: also put the cmd args in here 
echo $$ > .guard-jruby-rspec

#tail -n +0 -f .guard-jruby-rspec-pipe | { sed "/EOF/ q" && kill $$ ;}
tail -F .guard-jruby-rspec-pipe